### ISSUE TITLE
Deploy error on S3 bucket located in eu-west-3 region (Paris)

### ISSUE THREAD

**Issue by aritgithub** [platform-team/aws-maven#15]
All is configured correctly like many other projects that deploy on S3 buckets located in other regions. With a bucket located in eu-west-3 region (Paris) the "mvn deploy" reports this 403 Access Denied error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project projectxxx: Failed to deploy artifacts: Could not transfer artifact com.teamsystem.legal:projectxxx:jar:1.2.2 from/to my-aws-maven-repository-realeases (s3://my-aws-maven-repository/xxx): Cannot write directory 'xxx/': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 0DBD578631093ED7; S3 Extended Request ID: Pi3MAxRy/GqYZHySHII2dszWDDfBQpAWUOVoxCn8XL51CKfEeYp9s88w6W1ZiwjevvWy4=) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project projectxxx: Failed to deploy artifacts: Could not transfer artifact com.teamsystem.legal:projectxxx:jar:1.2.2 from/to my-aws-maven-repository-realeases (s3://my-aws-maven-repository/xxx): Cannot write directory 'xxx/'

Is this a region related problem?

**Comment by moleksyuk** [comment]
@aritgithub no,

We also have bucket in eu-west-3 and don't have any problems. 
Check that you use correct aws keys. And run mvn with debug info.

**Comment by aritgithub** [comment]
user-agent:aws-sdk-java/1.11.276 Mac_OS_X/10.11.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.131-b11 java/1.8.0_131

My pom.xml section:

</project>
    <build>
        <extensions>
            <extension>
                <groupId>com.github.platform-team</groupId>
                <artifactId>aws-maven</artifactId>
                <version>6.0.0</version>
            </extension>
        </extensions>
        ...
    </build>
    ...
    <distributionManagement>
        <repository>
            <id>sjs-aws-maven-repository-realeases</id>
            <name>AWS Snapshot Repository</name>
            <url>s3://my-aws-maven-repository/xxx</url>
        </repository>
    </distributionManagement>
</project>

My deploy command:

mvn -Daws.accessKeyId=XXXXXXXXX -Daws.secretKey=YYYYYYYYYYYYYYYY -X deploy

reports the 403 Access Denied error.

The similar operation with "aws s3 cp ... " command and same credentials works well.

**Comment by aritgithub** [comment]
Sorry, wrong configuration of my bucket.
But, why do I have to set the flag [Public Access Settings -> Manage public access control list (ACLs) -> Block new public ACLs and uploading public objects] to False for the deploy to work?

**Comment by moleksyuk** [comment]
@aritgithub sorry, but I don't have deep knowledge how it works. I've just forked and fixed issues we have during usage of this plugin. Probably you should raise this question to creators.

**Comment by aritgithub** [comment]
Ok, thanks, I will.

**Comment by aritgithub** [comment]
Good news:
https://github.com/spring-projects/aws-maven/issues/70
A developer has already prepared a fix for the problem I reported.

**Comment by moleksyuk** [comment]
@aritgithub 
1. Upstream project is dead (that's why we forked it)
2. Our fork also almost dead because I don't have enough time to merge opened pull request. Also we migrated to gradle and don't have any problems anymore. 😄

**Comment by jeugene** [comment]
I fixed this and sent fix PR a month ago? This is just pending PR merge.
Can you folks review PR and merge?

Joe
